[book]
title = "The Toka Programming Language Guide"
authors = ["lumicore-dev"]
language = "en"

[output.html]
git-repository-url = "https://github.com/tokalang/toka"
additional-js = ["theme/toka.js"]
